from __future__ import annotations

from datetime import datetime
from io import BytesIO
from re import sub
from typing import Any

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill
from openpyxl.utils import get_column_letter


MAX_EXPORT_ROWS = 20000


def clean_text(value: Any) -> str:
    if value is None:
        return ""
    return str(value).strip()


def safe_filename(value: str, ext: str) -> str:
    base = sub(r"[^A-Za-z0-9._-]+", "-", value.strip().lower()).strip("-") or "ntec-report"
    stamp = datetime.now().strftime("%Y%m%d-%H%M")
    return f"{base}-{stamp}.{ext}"


def _sheet_name(value: str, fallback: str) -> str:
    name = sub(r"[\[\]:*?/\\]", " ", clean_text(value) or fallback).strip()
    return (name[:31] or fallback)


def _sections(payload: dict) -> list[dict]:
    sections = payload.get("sections")
    if isinstance(sections, list) and sections:
        return sections
    return [{
        "title": payload.get("title") or "Report",
        "columns": payload.get("columns") or [],
        "rows": payload.get("rows") or [],
    }]


def _filters(payload: dict) -> list[tuple[str, str]]:
    filters = payload.get("filters") or []
    out: list[tuple[str, str]] = []
    for item in filters:
        if not isinstance(item, dict):
            continue
        label = clean_text(item.get("label"))
        value = clean_text(item.get("value"))
        if label and value:
            out.append((label, value))
    return out


def _summary(payload: dict) -> list[tuple[str, str]]:
    summary = payload.get("summary") or []
    out: list[tuple[str, str]] = []
    for item in summary:
        if not isinstance(item, dict):
            continue
        label = clean_text(item.get("label"))
        value = clean_text(item.get("value"))
        if label and value:
            out.append((label, value))
    return out


def build_excel_report(payload: dict) -> BytesIO:
    wb = Workbook()
    ws = wb.active
    ws.title = "Summary"

    title = clean_text(payload.get("title")) or "NTEC Report"
    generated_by = clean_text(payload.get("generatedBy")) or "System"
    generated_at = clean_text(payload.get("generatedAt")) or datetime.now().isoformat(timespec="seconds")

    ws.append([title])
    ws["A1"].font = Font(bold=True, size=16)
    ws.append(["Generated At", generated_at])
    ws.append(["Generated By", generated_by])
    ws.append([])

    filters = _filters(payload)
    if filters:
        ws.append(["Filters"])
        ws[ws.max_row][0].font = Font(bold=True)
        for label, value in filters:
            ws.append([label, value])
        ws.append([])

    summary = _summary(payload)
    if summary:
        ws.append(["Summary"])
        ws[ws.max_row][0].font = Font(bold=True)
        for label, value in summary:
            ws.append([label, value])

    for col in range(1, 4):
        ws.column_dimensions[get_column_letter(col)].width = 28

    used_names = {ws.title}
    for idx, section in enumerate(_sections(payload), start=1):
        raw_title = clean_text(section.get("title")) or f"Data {idx}"
        name = _sheet_name(raw_title, f"Data {idx}")
        while name in used_names:
            suffix = f" {idx}"
            name = f"{name[:31 - len(suffix)]}{suffix}"
        used_names.add(name)
        sheet = wb.create_sheet(name)

        columns = [c for c in section.get("columns", []) if isinstance(c, dict)]
        rows = section.get("rows") or []
        if not columns and rows:
            columns = [{"key": key, "label": key} for key in rows[0].keys()]

        sheet.append([clean_text(c.get("label")) or clean_text(c.get("key")) for c in columns])
        for cell in sheet[1]:
            cell.font = Font(bold=True, color="FFFFFF")
            cell.fill = PatternFill("solid", fgColor="4F46E5")

        for row in rows[:MAX_EXPORT_ROWS]:
            if not isinstance(row, dict):
                continue
            sheet.append([row.get(c.get("key")) for c in columns])

        for col_idx, column in enumerate(columns, start=1):
            label = clean_text(column.get("label")) or clean_text(column.get("key"))
            max_len = max([len(label)] + [
                len(clean_text(row.get(column.get("key"))))
                for row in rows[:200]
                if isinstance(row, dict)
            ])
            sheet.column_dimensions[get_column_letter(col_idx)].width = min(max(max_len + 2, 12), 42)
        sheet.freeze_panes = "A2"

    out = BytesIO()
    wb.save(out)
    out.seek(0)
    return out


def build_pdf_report(payload: dict) -> BytesIO:
    title = clean_text(payload.get("title")) or "NTEC Report"
    generated_by = clean_text(payload.get("generatedBy")) or "System"
    generated_at = clean_text(payload.get("generatedAt")) or datetime.now().isoformat(timespec="seconds")

    lines = [
        title,
        f"Generated at {generated_at} by {generated_by}",
        "",
    ]
    filters = _filters(payload)
    if filters:
        lines.append("Filters")
        lines.extend(f"{label}: {value}" for label, value in filters)
        lines.append("")
    summary = _summary(payload)
    if summary:
        lines.append("Summary")
        lines.extend(f"{label}: {value}" for label, value in summary)
        lines.append("")

    for section in _sections(payload):
        columns = [c for c in section.get("columns", []) if isinstance(c, dict)]
        rows = [r for r in (section.get("rows") or []) if isinstance(r, dict)]
        if not columns and rows:
            columns = [{"key": key, "label": key} for key in rows[0].keys()]
        if not columns:
            continue
        lines.append(clean_text(section.get("title")) or "Data")
        headers = [clean_text(c.get("label")) or clean_text(c.get("key")) for c in columns]
        lines.append(" | ".join(headers))
        lines.append("-" * min(120, max(24, sum(len(h) for h in headers) + 3 * len(headers))))
        for row in rows[:120]:
            values = [clean_text(row.get(c.get("key"))) for c in columns]
            lines.extend(_wrap_pdf_line(" | ".join(values), 132))
        if len(rows) > 120:
            lines.append(f"Showing first 120 of {len(rows)} rows. Use Excel for the full export.")
        lines.append("")

    return _render_text_pdf(lines)


def _wrap_pdf_line(line: str, limit: int) -> list[str]:
    if len(line) <= limit:
        return [line]
    chunks = []
    rest = line
    while len(rest) > limit:
        cut = rest.rfind(" ", 0, limit)
        if cut < limit // 2:
            cut = limit
        chunks.append(rest[:cut].rstrip())
        rest = rest[cut:].lstrip()
    if rest:
        chunks.append(rest)
    return chunks


def _pdf_escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")


def _render_text_pdf(lines: list[str]) -> BytesIO:
    width = 842
    height = 595
    margin = 36
    line_height = 12
    max_lines = int((height - (margin * 2)) / line_height)
    pages = [lines[i:i + max_lines] for i in range(0, len(lines), max_lines)] or [[]]

    objects: list[bytes] = []
    page_ids = []
    for page_lines in pages:
        commands = ["BT", "/F1 9 Tf", f"{margin} {height - margin} Td", "12 TL"]
        for line in page_lines:
            commands.append(f"({_pdf_escape(line[:180])}) Tj")
            commands.append("T*")
        commands.append("ET")
        stream = "\n".join(commands).encode("latin-1", "replace")
        content_id = len(objects) + 1
        objects.append(b"<< /Length " + str(len(stream)).encode() + b" >>\nstream\n" + stream + b"\nendstream")
        page_id = len(objects) + 1
        page_ids.append(page_id)
        objects.append(
            f"<< /Type /Page /Parent 0 0 R /MediaBox [0 0 {width} {height}] "
            f"/Resources << /Font << /F1 0 0 R >> >> /Contents {content_id} 0 R >>".encode()
        )

    font_id = len(objects) + 1
    objects.append(b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>")
    pages_id = len(objects) + 1
    kids = " ".join(f"{pid} 0 R" for pid in page_ids)
    objects.append(f"<< /Type /Pages /Kids [{kids}] /Count {len(page_ids)} >>".encode())
    catalog_id = len(objects) + 1
    objects.append(f"<< /Type /Catalog /Pages {pages_id} 0 R >>".encode())

    patched = []
    for obj in objects:
        patched.append(
            obj.replace(b"/Parent 0 0 R", f"/Parent {pages_id} 0 R".encode())
               .replace(b"/F1 0 0 R", f"/F1 {font_id} 0 R".encode())
        )

    out = BytesIO()
    out.write(b"%PDF-1.4\n")
    offsets = [0]
    for idx, obj in enumerate(patched, start=1):
        offsets.append(out.tell())
        out.write(f"{idx} 0 obj\n".encode())
        out.write(obj)
        out.write(b"\nendobj\n")
    xref = out.tell()
    out.write(f"xref\n0 {len(patched) + 1}\n".encode())
    out.write(b"0000000000 65535 f \n")
    for offset in offsets[1:]:
        out.write(f"{offset:010d} 00000 n \n".encode())
    out.write(
        f"trailer\n<< /Size {len(patched) + 1} /Root {catalog_id} 0 R >>\n"
        f"startxref\n{xref}\n%%EOF\n".encode()
    )
    out.seek(0)
    return out
